import {
  ACTIVITY_FREQUENCY_OPTIONS,
  ACTIVITY_LEVEL_OPTIONS,
  ADHERENCE_OPTIONS,
  ANALYSIS_TYPE_OPTIONS,
  CONTINUATION_OPTIONS,
  DOMINANCE_OPTIONS,
  ENERGY_LEVEL_OPTIONS,
  EVALUATION_FREQUENCY_OPTIONS,
  GENDER_OPTIONS,
  MAIN_OBJECTIVE_OPTIONS,
  YES_NO_OPTIONS,
} from "@/lib/form-field-presets";
import type { FormFieldDefinition } from "@/types/form-template";

export const DEFAULT_FORM_TEMPLATES: Record<
  string,
  { name: string; fields: FormFieldDefinition[] }
> = {
  follow_up: {
    name: "Formulario de seguimiento",
    fields: [
      {
        id: "currentWeight",
        name: "currentWeight",
        label: "Peso actual (kg)",
        type: "number",
        required: true,
        step: 1,
        min: 20,
        max: 300,
      },
      {
        id: "energyLevel",
        name: "energyLevel",
        label: "Nivel de energía",
        type: "select",
        required: true,
        step: 1,
        options: ENERGY_LEVEL_OPTIONS,
      },
      {
        id: "adherence",
        name: "adherence",
        label: "¿Cómo seguiste el plan?",
        type: "select",
        required: true,
        step: 1,
        options: ADHERENCE_OPTIONS,
      },
      {
        id: "symptoms",
        name: "symptoms",
        label: "Síntomas o molestias",
        type: "textarea",
        required: true,
        minLength: 3,
        step: 1,
        placeholder: "Describe síntomas o escribe «ninguno»",
      },
      {
        id: "notes",
        name: "notes",
        label: "Algo más que quieras comentar",
        type: "textarea",
        required: true,
        minLength: 3,
        step: 1,
        colSpan: 2,
      },
    ],
  },

  nutrition: {
    name: "Primera consulta nutricional",
    fields: [
      {
        id: "fullName",
        name: "fullName",
        label: "Nombre completo",
        type: "text",
        required: true,
        step: 2,
      },
      {
        id: "phone",
        name: "phone",
        label: "Teléfono (con código de área)",
        type: "tel",
        required: true,
        step: 2,
      },
      {
        id: "gender",
        name: "gender",
        label: "Sexo",
        type: "select",
        required: true,
        step: 2,
        options: GENDER_OPTIONS,
      },
      {
        id: "birthDate",
        name: "birthDate",
        label: "Fecha de nacimiento",
        type: "date",
        required: true,
        step: 2,
      },
      {
        id: "consultationReason",
        name: "consultationReason",
        label: "¿Qué te trae a consulta hoy?",
        type: "textarea",
        required: true,
        minLength: 5,
        step: 3,
        colSpan: 2,
      },
      {
        id: "dietDescription",
        name: "dietDescription",
        label: "¿Cómo describirías tu alimentación habitual?",
        type: "textarea",
        required: true,
        minLength: 5,
        step: 3,
        colSpan: 2,
      },
      {
        id: "dietaryRestrictions",
        name: "dietaryRestrictions",
        label: "Restricciones alimentarias, alergias o intolerancias",
        type: "textarea",
        required: true,
        minLength: 3,
        step: 3,
        colSpan: 2,
      },
      {
        id: "activityLevel",
        name: "activityLevel",
        label: "Nivel de actividad física",
        type: "select",
        required: true,
        step: 4,
        options: ACTIVITY_LEVEL_OPTIONS,
      },
      {
        id: "activityFrequency",
        name: "activityFrequency",
        label: "Frecuencia de actividad",
        type: "select",
        required: true,
        step: 4,
        options: ACTIVITY_FREQUENCY_OPTIONS,
      },
      {
        id: "sportsPracticed",
        name: "sportsPracticed",
        label: "¿Practicas algún deporte?",
        type: "text",
        required: true,
        minLength: 2,
        step: 4,
      },
      {
        id: "reservedSlotNote",
        name: "reservedSlotNote",
        label: "Turno reservado (fecha/hora)",
        type: "text",
        required: true,
        step: 4,
        colSpan: 2,
      },
      {
        id: "continuationPreference",
        name: "continuationPreference",
        label: "¿Cómo te gustaría continuar luego de la primera consulta?",
        type: "radio",
        required: true,
        step: 4,
        colSpan: 2,
        options: CONTINUATION_OPTIONS,
      },
    ],
  },

  anthropometry: {
    name: "Formulario de antropometría",
    fields: [
      {
        id: "consentAccepted",
        name: "consentAccepted",
        label:
          "He leído y doy mi consentimiento para participar en la evaluación antropométrica",
        type: "checkbox",
        required: true,
        step: 1,
        colSpan: 2,
        helpText:
          "Toda la información será tratada con confidencialidad. Puedes abandonar el proceso en cualquier momento.",
      },
      {
        id: "fullName",
        name: "fullName",
        label: "Nombre completo",
        type: "text",
        required: true,
        step: 2,
      },
      {
        id: "consultationReason",
        name: "consultationReason",
        label: "Motivo de consulta",
        type: "text",
        required: true,
        minLength: 5,
        step: 2,
        colSpan: 2,
      },
      {
        id: "phone",
        name: "phone",
        label: "Teléfono (con código de área)",
        type: "tel",
        required: true,
        step: 2,
      },
      {
        id: "gender",
        name: "gender",
        label: "Sexo",
        type: "select",
        required: true,
        step: 2,
        options: GENDER_OPTIONS,
      },
      {
        id: "birthDate",
        name: "birthDate",
        label: "Fecha de nacimiento",
        type: "date",
        required: true,
        step: 2,
      },
      {
        id: "previousAnthropometry",
        name: "previousAnthropometry",
        label: "¿Alguna vez te realizaste una antropometría?",
        type: "select",
        required: true,
        step: 3,
        options: YES_NO_OPTIONS,
      },
      {
        id: "dominantHand",
        name: "dominantHand",
        label: "Mano dominante",
        type: "select",
        required: true,
        step: 3,
        options: DOMINANCE_OPTIONS,
      },
      {
        id: "dominantFoot",
        name: "dominantFoot",
        label: "Pie dominante",
        type: "select",
        required: true,
        step: 3,
        options: DOMINANCE_OPTIONS,
      },
      {
        id: "activityLevel",
        name: "activityLevel",
        label: "Nivel de actividad física",
        type: "select",
        required: true,
        step: 3,
        options: ACTIVITY_LEVEL_OPTIONS,
      },
      {
        id: "activityFrequency",
        name: "activityFrequency",
        label: "Frecuencia de actividad",
        type: "select",
        required: true,
        step: 3,
        options: ACTIVITY_FREQUENCY_OPTIONS,
      },
      {
        id: "sportsPracticed",
        name: "sportsPracticed",
        label: "¿Practicas algún deporte?",
        type: "text",
        required: true,
        minLength: 2,
        step: 3,
        colSpan: 2,
      },
      {
        id: "reportAnalysisTypes",
        name: "reportAnalysisTypes",
        label: "Tipo de análisis deseado en el informe",
        type: "checkbox-group",
        required: true,
        step: 4,
        colSpan: 2,
        options: ANALYSIS_TYPE_OPTIONS,
      },
      {
        id: "mainObjective",
        name: "mainObjective",
        label: "Objetivo principal",
        type: "select",
        required: true,
        step: 4,
        options: MAIN_OBJECTIVE_OPTIONS,
      },
      {
        id: "evaluationFrequency",
        name: "evaluationFrequency",
        label: "Frecuencia deseada de evaluación",
        type: "select",
        required: true,
        step: 4,
        options: EVALUATION_FREQUENCY_OPTIONS,
      },
      {
        id: "reservedSlotNote",
        name: "reservedSlotNote",
        label: "Turno reservado (fecha/hora)",
        type: "text",
        required: true,
        step: 5,
        colSpan: 2,
      },
      {
        id: "procedureQuestions",
        name: "procedureQuestions",
        label: "Dudas o inquietudes sobre el procedimiento",
        type: "textarea",
        required: true,
        minLength: 5,
        step: 5,
        colSpan: 2,
      },
    ],
  },

  training: {
    name: "Formulario de entrenamiento",
    fields: [
      {
        id: "consentAccepted",
        name: "consentAccepted",
        label:
          "Confirmo que la información es verídica y autorizo su uso para diseñar mi plan de entrenamiento",
        type: "checkbox",
        required: true,
        step: 1,
        colSpan: 2,
      },
      {
        id: "fullName",
        name: "fullName",
        label: "Nombre completo",
        type: "text",
        required: true,
        step: 2,
      },
      {
        id: "consultationReason",
        name: "consultationReason",
        label: "Motivo de consulta / objetivos",
        type: "textarea",
        required: true,
        minLength: 5,
        step: 2,
        colSpan: 2,
      },
      {
        id: "phone",
        name: "phone",
        label: "Teléfono (con código de área)",
        type: "tel",
        required: true,
        step: 2,
      },
      {
        id: "gender",
        name: "gender",
        label: "Sexo",
        type: "select",
        required: true,
        step: 2,
        options: GENDER_OPTIONS,
      },
      {
        id: "birthDate",
        name: "birthDate",
        label: "Fecha de nacimiento",
        type: "date",
        required: true,
        step: 2,
      },
      {
        id: "previousAnthropometry",
        name: "previousAnthropometry",
        label: "¿Te realizaste antropometría antes?",
        type: "select",
        required: true,
        step: 3,
        options: YES_NO_OPTIONS,
      },
      {
        id: "dominantHand",
        name: "dominantHand",
        label: "Mano dominante",
        type: "select",
        required: true,
        step: 3,
        options: DOMINANCE_OPTIONS,
      },
      {
        id: "dominantFoot",
        name: "dominantFoot",
        label: "Pie dominante",
        type: "select",
        required: true,
        step: 3,
        options: DOMINANCE_OPTIONS,
      },
      {
        id: "activityLevel",
        name: "activityLevel",
        label: "Nivel de actividad física",
        type: "select",
        required: true,
        step: 3,
        options: ACTIVITY_LEVEL_OPTIONS,
      },
      {
        id: "activityFrequency",
        name: "activityFrequency",
        label: "Frecuencia de entrenamiento",
        type: "select",
        required: true,
        step: 3,
        options: ACTIVITY_FREQUENCY_OPTIONS,
      },
      {
        id: "sportsPracticed",
        name: "sportsPracticed",
        label: "Deportes o actividades que practicas",
        type: "text",
        required: true,
        minLength: 2,
        step: 3,
        colSpan: 2,
      },
      {
        id: "reportAnalysisTypes",
        name: "reportAnalysisTypes",
        label: "Información complementaria deseada",
        type: "checkbox-group",
        required: true,
        step: 4,
        colSpan: 2,
        options: ANALYSIS_TYPE_OPTIONS,
      },
      {
        id: "mainObjective",
        name: "mainObjective",
        label: "Objetivo principal",
        type: "select",
        required: true,
        step: 4,
        options: MAIN_OBJECTIVE_OPTIONS,
      },
      {
        id: "evaluationFrequency",
        name: "evaluationFrequency",
        label: "Frecuencia deseada de seguimiento",
        type: "select",
        required: true,
        step: 4,
        options: EVALUATION_FREQUENCY_OPTIONS,
      },
      {
        id: "reservedSlotNote",
        name: "reservedSlotNote",
        label: "Turno reservado (fecha/hora)",
        type: "text",
        required: true,
        step: 5,
        colSpan: 2,
      },
      {
        id: "procedureQuestions",
        name: "procedureQuestions",
        label: "Lesiones, limitaciones o dudas",
        type: "textarea",
        required: true,
        minLength: 5,
        step: 5,
        colSpan: 2,
      },
    ],
  },

  intake: {
    name: "Formulario de ingreso (anamnesis)",
    fields: [
      {
        id: "birthDate",
        name: "birthDate",
        label: "Fecha de nacimiento",
        type: "date",
        required: true,
        step: 1,
      },
      {
        id: "gender",
        name: "gender",
        label: "Género",
        type: "select",
        required: true,
        step: 1,
        options: [
          { value: "femenino", label: "Femenino" },
          { value: "masculino", label: "Masculino" },
          { value: "otro", label: "Otro" },
          { value: "prefiero_no_decir", label: "Prefiero no decir" },
        ],
      },
      {
        id: "height",
        name: "height",
        label: "Estatura (cm)",
        type: "number",
        required: true,
        min: 50,
        max: 250,
        step: 1,
      },
      {
        id: "occupation",
        name: "occupation",
        label: "Ocupación",
        type: "text",
        required: true,
        minLength: 2,
        step: 1,
      },
      {
        id: "emergencyPhone",
        name: "emergencyPhone",
        label: "Teléfono de emergencia",
        type: "tel",
        required: true,
        step: 1,
        colSpan: 2,
      },
      {
        id: "conditions",
        name: "conditions",
        label: "Enfermedades o condiciones actuales",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 2,
        colSpan: 2,
        placeholder: "Ej: hipotiroidismo… o «ninguna»",
      },
      {
        id: "surgeries",
        name: "surgeries",
        label: "Cirugías previas",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 2,
        colSpan: 2,
      },
      {
        id: "medications",
        name: "medications",
        label: "Medicamentos actuales",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 2,
        colSpan: 2,
      },
      {
        id: "familyHistory",
        name: "familyHistory",
        label: "Antecedentes familiares relevantes",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 2,
        colSpan: 2,
      },
      {
        id: "allergyFood",
        name: "allergyFood",
        label: "Alergias alimentarias",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 3,
        colSpan: 2,
      },
      {
        id: "allergyDrug",
        name: "allergyDrug",
        label: "Alergias a medicamentos",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 3,
        colSpan: 2,
      },
      {
        id: "allergyOther",
        name: "allergyOther",
        label: "Otras alergias o intolerancias",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 3,
        colSpan: 2,
      },
      {
        id: "mealsPerDay",
        name: "mealsPerDay",
        label: "Comidas al día",
        type: "number",
        required: true,
        min: 1,
        max: 10,
        step: 4,
      },
      {
        id: "waterLiters",
        name: "waterLiters",
        label: "Agua (litros/día)",
        type: "number",
        required: true,
        min: 0,
        max: 10,
        step: 4,
      },
      {
        id: "eatingOutFrequency",
        name: "eatingOutFrequency",
        label: "¿Con qué frecuencia comes fuera?",
        type: "select",
        required: true,
        step: 4,
        options: [
          { value: "nunca", label: "Nunca" },
          { value: "rara_vez", label: "Rara vez" },
          { value: "1-2_semana", label: "1–2 veces por semana" },
          { value: "3+_semana", label: "3+ veces por semana" },
        ],
      },
      {
        id: "skipsBreakfast",
        name: "skipsBreakfast",
        label: "Sí, con frecuencia salto el desayuno",
        type: "checkbox",
        required: false,
        step: 4,
      },
      {
        id: "dietNotes",
        name: "dietNotes",
        label: "Notas adicionales sobre alimentación",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 4,
        colSpan: 2,
      },
      {
        id: "activityFrequency",
        name: "activityFrequency",
        label: "Frecuencia de actividad física",
        type: "select",
        required: true,
        step: 5,
        options: [
          { value: "sedentario", label: "Sedentario" },
          { value: "1-2_dias", label: "1–2 días por semana" },
          { value: "3-4_dias", label: "3–4 días por semana" },
          { value: "5+_dias", label: "5+ días por semana" },
        ],
      },
      {
        id: "activityType",
        name: "activityType",
        label: "Tipo de actividad",
        type: "text",
        required: true,
        minLength: 2,
        step: 5,
        placeholder: "Ej: caminata, gym, yoga…",
      },
      {
        id: "hoursPerWeek",
        name: "hoursPerWeek",
        label: "Horas activas por semana",
        type: "number",
        required: true,
        min: 0,
        max: 40,
        step: 5,
      },
      {
        id: "sedentaryHours",
        name: "sedentaryHours",
        label: "Horas sedentarias por día",
        type: "number",
        required: true,
        min: 0,
        max: 24,
        step: 5,
      },
      {
        id: "goals",
        name: "goals",
        label: "¿Cuáles son tus objetivos?",
        type: "textarea",
        required: true,
        minLength: 10,
        step: 6,
        colSpan: 2,
      },
      {
        id: "supplements",
        name: "supplements",
        label: "Suplementos que consumes",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 6,
        colSpan: 2,
        placeholder: "Ej: proteína, multivitamínico… o «ninguno»",
      },
      {
        id: "supplementsNotes",
        name: "supplementsNotes",
        label: "Notas sobre suplementos",
        type: "textarea",
        required: true,
        minLength: 2,
        step: 6,
        colSpan: 2,
      },
    ],
  },
};

export const FORM_TYPE_TO_TEMPLATE: Record<string, string> = {
  anthropometry: "anthropometry",
  nutrition: "nutrition",
  training: "training",
  follow_up: "follow_up",
  intake: "intake",
};
